version: "3.9"

networks:
  postgres-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      PGDATA: /data/postgres
    volumes:
      - ./volumes/postgres:/data/postgres
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    ports:
      - 16543:80
    networks:
      - postgres-network
    depends_on:
      - postgres
    restart: unless-stopped